export const errorCode =  {
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    EMAIL_EXISTS: "EMAIL_EXISTS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    METHOD_ARGUMENT_NOT_VALID: "METHOD_ARGUMENT_NOT_VALID",
    TOKEN_NOT_EXISTS: "TOKEN_NOT_EXISTS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID"
}
