services:
  db:
    image: mysql
    container_name: to-do-db
    env_file: to-do-api/db.env
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"

  mail:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  config:
    build:
      context: ./to-do-config-server
    container_name: to-do-config-server
    env_file:
      - to-do-config-server/config.env
    healthcheck:
      test: "curl --fail --silent http://localhost:8087/actuator/health/readiness | grep UP || exit 1"
      start_period: 20s
      interval: 15s
      timeout: 10s
      retries: 10
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8087:8087"

  redis:
    image: redis:latest
    container_name: to-do-redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: to-do-redis-insight
    ports:
      - "5540:5540"

  api-1:
    build: ./to-do-api
    container_name: to-do-api-1
    env_file: to-do-api/api.env
    depends_on:
      config:
          condition: service_healthy
      db:
        condition: service_healthy
      mail:
        condition: service_healthy

    ports:
      - "8080:8080"

#  api-2:
#    build: ./to-do-api
#    container_name: to-do-api-2
#    env_file: api.env
#    depends_on:
#      - db
#      - mail
#
#  api-3:
#    build: ./to-do-api
#    container_name: to-do-api-3
#    env_file: api.env
#    depends_on:
#      - db
#      - mail

  nginx:
    image: nginx:latest
    container_name: to-do-nginx
    ports:
      # - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/
      - ./nginx/ssl:/etc/nginx/ssl/

  rabbitmq:
    image: rabbitmq:4-management
    container_name: to-do-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_running
    env_file:
      - to-do-api/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"

#  ui:
#    build:
#      context: to-do-ui/.
#    env_file:
#      - to-do-ui/ui.env
#    ports:
#      - "8080:8080"
volumes:
  data:
