services:
  db:
    image: mysql
    container_name: to-do-db
    env_file: db.env
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  mail:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  api:
    build: ./to-do-api
    container_name: to-do-api
    env_file: api.env
    # ports:
    #   - "8080:8080"
    depends_on:
      - db
      - mail

  nginx:
    image: nginx:latest
    container_name: to-do-nginx
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/
      - ./nginx/ssl:/etc/nginx/ssl/
    depends_on:
      - api

  ui:
    build:
      context: to-do-ui/.
    env_file:
      - ui.env
    ports:
      - "8080:8080"
volumes:
  data:
