services:
  db:
    image: mysql
    container_name: to-do-db
    env_file: db.env
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  mail:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  data:
