spring.application.name=to-do-api

#oauth2
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:https://localhost/login/oauth2/code/google}


#payos
payos.return-url=${PAYOS_RETURN_URL:http://localhost:8080/payos-return}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:8080/payos-cancel}

#ui
ui.url=${UI_URL:http://localhost:8080}