package com.viet.to_do_api.constant;

public enum ExceptionCode {
    EMAIL_EXISTS,
    INTERNAL_SERVER_ERROR,
    METHOD_ARGUMENT_NOT_VALID,
    TOKEN_NOT_EXISTS,
    TOKEN_EXPIRED,
    DISABLED_ACCOUNT,
    BAD_CREDENTIALS,
    TOKEN_INVALID,
    AUTHENTICATION_ERROR,
    FORBIDDEN,
    UNAUTHORIZED
}
