spring:
  application:
    name: to-do-config-server
  profiles:
    active: git
  #rabbitmq
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}

  cloud:
    config:
      server:
        #local
#        native:
#          search-locations: file:/home/${USER:viet}/Project/to-do-app-config
        # git
        git:
          clone-on-start: true
          force-pull: true
          timeout: 5
          uri: ${GITHUB_URL:https://github.com/nguyendangviet12022004/to-do-app-config.git}
          username: ${GITHUB_USERNAME:nguyendangviet12022004}
          password: ${GITHUB_TOKEN:GITHUB_TOKEN}
          default-label: main

#encrypt
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: ${ENCRYPT_KEY_STORE_PASSWORD:letMeIn}
    alias: ${ENCRYPT_KEY_STORE_ALIAS:serverKey}
    secret: ${ENCRYPT_KEY_STORE_SECRET:letMeIn}


server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: "*"
